name: Publish NPM

on: 
  workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the selected branch
      uses: actions/checkout@v2
      with:
        ref: main
        fetch-depth: 0
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '12.20'
    - name: Verify build
      run: ./gradlew build
    - name: Setup Node token
      run: npm set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}
    - name: Publish Bridge NPM package
      working-directory: ./templating/src/main/js/bridge
      run: npm publish
    - name: Publish Bridge React NPM package
      working-directory: ./templating/src/main/js/bridge-react
      run: npm publish
    
